#!/usr/bin/env bash
# 01-create-ami.sh — Build the UE5.3 AMI using Packer.
# Outputs: AMI ID written to ../../Infra/environments/dev/ami_id.auto.tfvars
#
# Prerequisites:
#   - Packer >= 1.9  (https://developer.hashicorp.com/packer/install)
#   - AWS CLI configured for account 732231126129, region eu-west-1
#   - GitHub account linked to Epic Games (for UE5.3 source access)
#   - UE5_GITHUB_TOKEN env var if the repo is private
#
# Usage:
#   UE5_GITHUB_TOKEN=ghp_xxx ./scripts/phase4/01-create-ami.sh
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PACKER_DIR="$REPO_ROOT/Infra/packer"
TFVARS_FILE="$REPO_ROOT/Infra/environments/dev/ami_id.auto.tfvars"
MANIFEST="$PACKER_DIR/packer-manifest.json"
AWS_REGION="${AWS_REGION:-eu-west-1}"

echo "=== Phase 4 / Step 1: Build UE5.3 AMI ==="
echo "Region : $AWS_REGION"
echo "Packer : $(packer version 2>/dev/null || echo 'NOT FOUND — install from https://developer.hashicorp.com/packer/install')"
echo ""

# Warn about build time
echo "WARNING: UE5.3 build from source takes 4-8 hours and costs ~\$3-5 in EC2 spot fees."
echo "Press ENTER to continue or Ctrl-C to abort."
read -r

# Validate and build
cd "$PACKER_DIR"
packer init .
packer validate \
  -var "aws_region=$AWS_REGION" \
  ue5-build-ami.pkr.hcl

packer build \
  -var "aws_region=$AWS_REGION" \
  ${UE5_GITHUB_TOKEN:+-var "ue5_github_token=$UE5_GITHUB_TOKEN"} \
  ue5-build-ami.pkr.hcl

# Extract AMI ID from manifest
if [[ ! -f "$MANIFEST" ]]; then
  echo "ERROR: packer-manifest.json not found. Build may have failed." >&2
  exit 1
fi

AMI_ID=$(jq -r '.builds[-1].artifact_id' "$MANIFEST" | cut -d':' -f2)
echo ""
echo "=== AMI created: $AMI_ID ==="

# Write to tfvars for automatic pickup by Terraform
cat > "$TFVARS_FILE" <<EOF
# Auto-generated by scripts/phase4/01-create-ami.sh — $(date -u '+%Y-%m-%dT%H:%M:%SZ')
ami_id = "$AMI_ID"
EOF

echo "AMI ID written to: $TFVARS_FILE"
echo ""
echo "Next step: run scripts/phase4/02-compile-server.sh"
