# Variables for Development Environment

variable "project_name" {
  description = "Name of the project"
  type        = string
  default     = "hypermage-vr"
}

variable "aws_region" {
  description = "AWS region for deployment"
  type        = string
  default     = "eu-west-1"
}

variable "ami_id" {
  description = "UE5.3 build AMI ID (auto-generated by scripts/phase4/01-create-ami.sh into ami_id.auto.tfvars)"
  type        = string
  default     = ""
}
