default_agent: testcalc_Agent
agents:
  testcalc_Agent:
    name: testcalc_Agent
    language: python
    node_version: null
    entrypoint: C:\Users\j_e_a\OneDrive\Projects\Hypermage\Hypermage_VR\Agents\testcalc\src\main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/amd64
    container_runtime: null
    source_path: C:\Users\j_e_a\OneDrive\Projects\Hypermage\Hypermage_VR\Agents\testcalc\src
    aws:
      execution_role: arn:aws:iam::732231126129:role/AmazonBedrockAgentCoreSDKRuntime-eu-west-1-81c578ca1b
      execution_role_auto_create: false
      account: '732231126129'
      region: eu-west-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-732231126129-eu-west-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: testcalc_Agent-aTfL1qCuDn
      agent_arn: arn:aws:bedrock-agentcore:eu-west-1:732231126129:runtime/testcalc_Agent-aTfL1qCuDn
      agent_session_id: ce3cedec-e5dd-45ec-a401-75b6ec31f85b
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
